package p06_SimpleAnimation;

import java.awt.*;
import javax.swing.*;

// Being a JPanel, Ball cannot extent Thread. It must implement Runnable
// in order to executed in its own thread
public class Ball extends javax.swing.JPanel implements Runnable {
	
	private volatile int timeToSleep=50;
    private int x,y;
	
    
    private static final long serialVersionUID = 1L;
    public Ball() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                        
    // Variables declaration - do not modify                     
    // End of variables declaration                   

    @Override
    public void run() {
        this.setForeground(Color.BLUE);
        Dimension dim = this.getSize();
        x = dim.width/2;
        y = dim.height/2;
        while (true) {
            // move
            dim = this.getSize();
            x = (x+1)%dim.width;
            y = (y+1)%dim.height;
            this.repaint();
            // wait
            try {
                Thread.sleep(timeToSleep);
            }
            catch(InterruptedException ie) {}
        }
    }
    
    @Override
    public void paintComponent (Graphics g) {
        super.paintComponent(g);
        g.fillOval(x,y,20,20);
    }
    
    public void setTimeToSleep (int time) {
    	this.timeToSleep = time;
    }
    
    
    // sample (and simple) launcher.
	public static void main(String[] args) {

		EventQueue.invokeLater(new Runnable() {
			public void run() {
				JFrame frame = new JFrame("Moving ball");
				Ball b = new Ball();
				Thread th = new Thread(b);

				frame.getContentPane().add(b);
				frame.setSize(300, 300);
				frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				frame.setVisible(true);

				th.start();
			}
		});
	}
    
}
